openapi: 3.0.0
info:
  description: Authenticator
  version: 1.0.0
  title:  Authenticator Service
  contact:
    email: kiennt9696@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: alive
    description: Keepalive
  - name: login
    description: Login
  - name: user
    description: user management
paths:
  /:
    get:
      tags:
        - alive
      summary: Api keepalive
      description: Api keepalive
      operationId: authenticator.app.index
      responses:
        "200":
          description: Home quiz
          content:
            text/html:
              schema:
                type: string
  /ping:
    get:
      tags:
        - alive
      summary: Api keepalive
      description: Api keepalive
      operationId: authenticator.controllers.healthz.is_alive
      responses:
        "200":
          description: is alive
  /login:
    post:
      tags:
        - "login"
      summary: "log in with username and password"
      operationId: "authenticator.controllers.authentication.login"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        "200":
          description: User successfully submit the answer
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Login successfully"
                  session_token:
                    type: string
                    example: "abc"
  /user:
    post:
      tags:
        - "user"
      summary: "Add a user"
      operationId: "authenticator.controllers.user.create_user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                firstname:
                    type: string
                lastname:
                    type: string
              required:
                - username
                - password
      responses:
        "204":
          description: User is successfully created

servers:
  - url: http://0.0.0.0:8081/v1